---
title: "p8105_hw4_mp3652"
author: "MeOak Place"
date: "October 24, 2017"
output: html_document
---

```{r load_packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(data.table)
library(dplyr)
library(devtools)
library(DT)
library(forcats)
library(ggplot2)
library(ggridges)
library(ggthemes)
library(haven)
library(janitor)
library(knitr)
library(magrittr)
library(readr)
library(readxl)
library(reshape2)
```

###################################

Problem 1:  Pups

###################################


```{r importing data, warning = FALSE, message = FALSE}
pups_data = read_csv(file = "./data/FAS_pups.csv") %>% 
  clean_names() %>% 
  select(-c(2)) %>%                             #removing sex column as key is n/a
  arrange(litter_number)
pups_data

pups_data %>% 
  count()

##############
# avg ears
##############
ears = pups_data %>%            
  select(-c(3:5)) %>% 
  group_by(litter_number) %>% 
  mutate(
    "avg_pd_ears" = round(mean(pd_ears), 1)
    ) %>% 
  select(-c(2)) %>% 
  filter(!duplicated(litter_number))
ears


##############
# avg eyes
##############
eyes = pups_data %>%                            
  select(-c(2, 4, 5)) %>% 
  group_by(litter_number) %>% 
  mutate(
    "avg_pd_eyes" = round(mean(pd_eyes), 1)
    ) %>% 
  select(-c(2)) %>% 
  filter(!duplicated(litter_number))
eyes


##############
# avg pivot
##############
pivot = pups_data %>%
  select(-c(2, 3, 5)) %>% 
  group_by(litter_number) %>% 
  mutate(
    "avg_pd_pivot" = round(mean(pd_pivot), 1)
    ) %>% 
  select(-c(2)) %>% 
  filter(!duplicated(litter_number))
pivot


##############
# avg walk
##############
walk = pups_data %>%
  select(-c(2:4)) %>% 
  group_by(litter_number) %>% 
  mutate(
    "avg_pd_walk" = round(mean(pd_walk), 1)
    ) %>% 
  select(-c(2)) %>% 
  filter(!duplicated(litter_number))
walk

pups = data.frame(ears, pivot, walk, eyes) %>% #no merge() b/c joining 4 df's, not 2
  mutate("id" = labels(litter_number)) %>%
  select(-c(1,3,5,7)) 
str(pups)

pups %>% 
  count()
```

The original pups data set contained 'r pups_data %>% count()' observations; however, there were only `r pups %>% count()` distinct litter numbers.  As such, we assumed that the multiple entries for each pup were a result of multiple observers, each of whom uniquely recorded developmental landmarks. 

```{r Plot, warning = FALSE, message = FALSE}
#Josie's Collaboration
#ridge
pups %>%
  gather(key = landmark, value = average_days, avg_pd_ears:avg_pd_eyes) %>%
  ggplot(aes(y = landmark, x = average_days)) + geom_density_ridges() + 
  labs(
    title = "Average Days to Acheive Post-Natal Developmental Landmarks",
    x = "Average Days",
    y = "Developmental Landmark"
  )
```


